[workspace]
resolver = "2"
members = [
    "tokens",
    "traits",
    "utilities",
    "vesting",
    "xcm",
    "xtokens"
]

[patch.'https://github.com/w3f/ring-vrf']
bandersnatch_vrfs = { git = "https://github.com/w3f//ring-vrf.git", rev = "3ebdd261873da05124f4499c85a8e62d40411620"}